language: cpp
cache: ccache
sudo: required
dist: trusty

branches:
  only:
    - master

before_install:
  - sudo apt-get update

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test 
    packages:
      - g++-9
      
script:
  - CXX=/usr/bin/g++-9 CC=/usr/bin/gcc-9 cmake .
  - cmake --build .
  